const axios = require('axios')
const skills = [
    '.Net Architecture',
    'C# - CSharp-Programming',
    '.NET',
    'ASP.NET',
    'WinForms',
    'VB.NET',
    'WPF - Windows Presentation Foundation',
    'WF - Windows Workflow Foundation',
    '.NET Design Patterns',
    'ADO.NET',
    '.NET Enterprise Library',
    'WCF - Windows Communication Foundation',
    'ASP.NET MVC 2',
    'ADO.NET Entity Framework',
    'ASP.NET MVC 3',
    'ASP.NET MVC 4',
    'LINQ - Language Integrated Query',
    'NHibernate',
    '.NET Upgrade',
    '.NET Coded UI Test Builder',
    'BizTalk',
    'Biztalk - Architecting',
    'AppFabric',
    'BizTalk 2013',
    'BizTalk Monitoring Tools',
    'BizTalk ESB Toolkit',
    'Cloud-Microsoft Azure',
    'Cloud-SQL Azure',
    'MS Azure App Cloud computing Consulting',
    'Azure API Management',
    'Azure Web Apps',
    'Azure Mobile Apps',
    'Azure Logic Apps',
    'Azure API Apps',
    'Azure Cloud Services',
    'Azure Active Directory',
    'Azure Service Bus',
    'Azure IOT',
    'Azure Monitoring Tools',
    'Azure Microservices',
    'Azure Kubernetes Services',
    'FullStack Microsoft-Cloud Azure',
    'Azure SDK for Java',
    'Azure Cosmos DB',
    'Azure DevOps Server',
    'Application Lifecycle Management - ALM',
    'DevOps - Continuous Delivery',
    'Continuous Integration - Bamboo',
    'Docker Platform',
    'Cloud-Microsoft Azure DevOps',
    'Puppet for DevOps Apps',
    'Chef for DevOps Apps',
    'JS JavaScript Libraries for .Net',
    'Json.NET-JavaScript Object Notation for .Net',
    'CSS3',
    'TypeScript',
    'ASP.NET MVC 5',
    'Knockout JS',
    'Express JS',
    'UWP - Universal Windows Platform',
    'Microsoft Cortana SDK',
    'Microsoft Modern Apps Architecting',
    'ASP.NET Web API',
    'Angular 4.0',
    'ASP.NET Core',
    'AngularJS for .NET',
    'Bootstrap for .NET',
    'NodeJS for .NET',
    'Angular 5 MS',
    'FullStack Microsoft .NET Smart Web App',
    'Conversational AI',
    'LUIS - Microsoft Cognitive Service',
    '.NET Microservices',
    'ML.NET',
    'Xamarin Platform',
    'Sitecore',
    'Umbraco CMS - Content Management System',
    'SDL Tridion',
    'Sitefinity - Web Content Management',
    'Episerver CMS - Content Management System',
    'DNN CMS - Content Management System',
    'Aprimo ADAM - Digital Asset Management',
    'Kentico - Content Management System',
    'MSCRM Functional',
    'Microsoft Dynamics CRM 2011',
    'MS CRM Surround',
    'MSCRM Tech Advanced',
    'Microsoft Dynamics AX',
    'Microsoft Dynamics NAV',
    'Microsoft Dynamics CRM 2013',
    'Microsoft Dynamics CRM 2016 - Customization and Configuratio',
    'Microsoft Dynamics CRM 2016 - Sales',
    'Microsoft Dynamics 365 Customization and Configuration',
    'Microsoft Dynamics 365 for Sales',
    'MICROSOFT DYNAMICS CRM 2015',
    'Microsoft Dynamics 365 for Customer Service',
    'Microsoft Dynamics 365 for Project Service Automation',
    'Microsoft Social Engagement for Dynamics CRM',
    'Adxstudio Portal',
    'Microsoft Dynamics 365 for Operations - Finance',
    'MS Dynamics 365 for Operation - Distribution and Trade',
    'Microsoft Dynamics 365 for Operation - Retail',
    'Microsoft Dynamics AX 2012 - Trade and Logistics',
    'Microsoft Dynamics AX 2012 - Finance',
    'Microsoft Dynamics AX 2012 - Retail',
    'Microsoft Dynamics 365 Portals',
    'Microsoft CRM Solution Design',
    'Microsoft Dynamics - Project Management',
    'Microsoft Dynamics - Consulting',
    'FullStack Microsoft-Cloud Customer Experience-Dynamics365',
    'Microsoft Power Platform for Dynamics 365',
    'DevOps for Dynamics 365',
    'Microsoft Dynamics 365 AI for Sales',
    'Microsoft Dynamics 365 AI for Service',
    'Office 365 PowerShell',
    'Office 365 - SharePoint Online',
    'ADFS - Active Directory Federation Services',
    'Office 365 - Exchange Online',
    'Office 365 - Skype for Business',
    'Yammer',
    'Office 365 - OneDrive for Business',
    'Office 365 - Mailbox Migration',
    'Office 365 - Admin Center',
    'Office 365 - Exchange Online - Consulting',
    'FullStack Microsoft-Cloud-Modern Workplace-Office365',
    'Sharepoint Admin',
    'SharePoint Enterprise Search',
    'InfoPath',
    'SharePoint Migration',
    'MS Project Server',
    'SharePoint',
    'SharePoint 2010',
    'FAST Search',
    'SharePoint 2013',
    'Nintex Workflow for SharePoint',
    'K2.NET',
    'SharePoint Designer',
    'Excel Services',
    'Custom Web Parts',
    'Performance Point',
    'TeamCity',
    'SharePoint 2016',
    'Microsoft Project Online',
    'Microsoft Flow',
    'Microsoft PowerApps',
    'Microsoft Office Sway',
    'Microsoft Teams',
    'Office 365 - Planner',
    'Microsoft Office Delve',
    'Office 365 - Video',
    'Microsoft Stream',
    'Microsoft EPM - Enterprise Project Management',
    'ASP - Active Server Page',
    'Visual Basic-VB',
    'SQL Server',
    'HTML5',
    'Entity Framework',
    '.NET Framework',
    'jQuery',
    'AJAX',
    'Apache Maven',
    'C',
    'C++',
    'PHP',
    'PIVOTAL CLOUD FOUNDRY',
    'Microsoft PowerBI',
    'PYTHON',
    'React JS',
    'UNIX',
    'Performance Testing',
    'OSS Application Testing',
    'BAQA Digital Assurance',
    'Mainframe Testing',
    'Parasoft SOAtest',
    'Mobile Native Application Testing',
    'Microfocus LoadRunner',
    'Microfocus QTP - UFT Automation Testing',
    'Microfocus Application Life Cycle Management - HP Quality Center',
    'IBM Rational Performance Tester',
    'SOA Testing',
    'Test Automation',
    'Data Centric testing',
    'RFT - IBM Rational Functional Tester',
    'Application Testing',
    'SFDC Testing',
    'Usability Testing',
    'Test Project Management',
    'Project Management-BAS-QET',
    'VSTS CodedUI Automation Testing',
    'Retail App Testing',
    'Selenium',
    'Cloud Testing',
    'Jmeter',
    'dynaTrace',
    'IT Environment Management Support',
    'Microfocus Performance Center',
    'IT Environment Management',
    'Test Deployment Management',
    'Test Deployment',
    'CA Service Virtualization',
    'SOAP UI Testing',
    'Microfocus Service Virtualization',
    'Mobile App Test Automation',
    'Mobile App Performance Testing',
    'Performance Engineering Essentials',
    'Easy Automate Selenium',
    'Securities and Capital Markets Testing',
    'DB2 Testing',
    'Tosca Testsuite - Test Automation',
    'CA DevTest',
    'Worksoft Certify',
    'Accessibility Testing',
    'BDD - Behavioral Driven Development Testing',
    'Microfocus Service Test',
    'QC - ALM Admin',
    'Informatica ETL Testing',
    'Ab Initio ETL Testing',
    'Informatica ILM TDM',
    'Banking Testing',
    'Teradata Testing',
    'Insurance Testing',
    'Application Test Consulting',
    'Datastage ETL Testing',
    'IBM Optim Testing',
    'ETL Testing',
    'Microstrategy BI Testing',
    'Big Data Testing',
    'PEGA Testing',
    'ToscaÂ OSV-OrchestratedÂ Service Virtualization',
    'SDET',
    'Protractor',
    'Informatica master data management Testing',
    'IBM master data management Testing',
    'QuerySurge',
    'Informatica - Data validation option',
    'New Relic',
    'AppDynamics',
    'CA Application Performance Management',
    'Datadog',
    'Sensu',
    'Lean Functional Testing',
    'Bots Testing',
    'Artifical Intelligence Testing',
    'Virtual Reality and Augmented Reality Testing',
    'CA Test Data Management',
    'BI Automated Testing',
    'MS D365 Testing',
    'ServiceNow Testing',
    'Workday Testing',
    'Appium',
    'Consulting-BAS-QET',
    'Parasoft Virtualize',
    'FullStack SDET',
    'CA Blazemeter',
    'Microfocus  StormRunner',
    'Performance Engineering for Cloud',
    'Performance Engineering for Big Data Analytics',
    'Performance Engineering for SAP',
    'Performance Engineering for Mobile',
    'Performance Profiling',
    'Integrated Cloud Assurance',
    'Applitools Eyes',
    'AI/ML App Testing',
    'Microservice Assurance',
    'ALM Octane',
    'Rapid Test Design',
    'Smart Data Solution',
    'Espresso',
    'Headspin',
    'XCUITest',
    'Qtest',
    'SOASTA CLoudTEst',
    'Predictive Quality Analytics',
    'Modernization Automation Testing',
    'Functionize VAE',
    'Katalon Studio',
    'Cypress',
    'Sealights',
    'Postman',
    'Silk Performer',
    'Gatling',
    'Chaos Monkey',
    'ServiceV Pro',
    'WireMock',
    'Mockito',
    'Pact',
    'Java',
    'TestNg',
    'Maven',
    'GitHub',
    'Jenkins',
    'SonarQube',
    'RestAssured',
    'Log4J',
    'Javadoc',
    'Jira',
    'SQL Programming language',
    'Agile testing',
    'Node JS',
    'HTML Programming language',
    'POS Testing',
    'Microsoft TFS',
    'SAP BODS'
]
​
const url = 'https://api.topcoder.com/v5/skills'
​
async function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
​
async function createSkill() {
  for (let i = 0; i < skills.length; i++) {
    const name = skills[i]
    console.log(i)
​
    try {
      await axios.post(url, {
        skillProviderId: '37f6fb04-b53c-4039-815e-b0ac158324e1',
        name
      }, {
        headers: {
          Authorization: 'Bearer '
        }
      })
    } catch (error) {
      console.log('Error for ', name)
      console.log(error)
    }
    await sleep(3000)
  }
}
​
createSkill()